### ISSUE TITLE
Roadmap to support Pydantic v2

### ISSUE THREAD

**Issue by teohm** [meltano/edk#145]
This is how we install Airflow in Meltano:

```yaml
# utilities.meltano.yml

plugins:
  utilities:
  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow[amazon,opsgenie]==2.7.0
```

The problem is we cannot upgrade Airflow to 2.7.1 or later.

The reason is the constraints file of Airflow 2.7.1 or later includes **Pydantic v2**, see:
- https://raw.githubusercontent.com/apache/airflow/constraints-2.7.1/constraints-no-providers-3.11.txt
- https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-no-providers-3.11.txt

And **[airflow-ext](https://github.com/meltano/airflow-ext)** is built on top `edk` package, which requires **Pydantic v1**:

```
[tool.poetry.dependencies]
python = "<3.12,>=3.7"
structlog = ">=21,<24"
PyYAML = "^6.0.0"
pydantic = ">=1.9.0,<2" 
devtools = ">=0.9.0,<1"
```
(extracted from: https://github.com/meltano/edk/blob/main/pyproject.toml#L44-L49)

Question: Is there a quick way to workaround and upgrade Airflow to 2.7.1 or 2.7.2 in Meltano?
