### ISSUE TITLE
Explain how to tie into meltano project

### ISSUE THREAD

**Issue by twiclo** [meltano/edk#397]
I just spent a considerable amount of time figuring out how to properly add my custom extension to my greater meltano project. A little section at the end of "Getting Started" would be nice.

For those seeing this in the future this is what needs to be added to your meltano.yml to import your custom extension/utility built with the EDK:
```
  utilities:
    - name: scp-ext
      namespace: who-cares
      pip_url: '../scp-ext'
      executable: scp
```
